version: '3.9'

services:
  stubby4j:
    image: kalleodocker/stubby4j:1.1
    ports:
      - "8882:8882"
    environment:
      STUBBY_PORT: 8882
    volumes:
      - ./stubby.yml:/usr/local/stubby.yml
    networks:
      - bridged

networks:
  bridged:
    driver: bridge
    ipam:
      config:
        - subnet: 10.10.1.0/24