version: '3'

services:
  public-service:
    image: public-service:0.0.1-SNAPSHOT
    container_name: public-service
    networks:
      srm:
        ipv4_address: 172.32.0.101
    expose:
      - 8080

  subscription-api:
    image: subscription-api:0.0.1-SNAPSHOT
    container_name: subscription-api
    networks:
      srm:
        ipv4_address: 172.32.0.103
    expose:
      - 8081

  email-service:
    image: email-service:0.0.1-SNAPSHOT
    container_name: email-service
    networks:
      srm:
        ipv4_address: 172.32.0.102


networks:
  srm:
    driver: bridge
    driver_opts:
        com.docker.network.enable_ipv4: "true"
    ipam:
      driver: default
      config:
        - subnet: 172.32.0.0/16