version: '3'

services:
  public-service:
    image: public-service:0.0.1-SNAPSHOT
    container_name: public-service
    ports:
      - 8080:8080
    depends_on:
      - "subscription-api"

  email-service:
    image: email-service:0.0.1-SNAPSHOT
    container_name: email-service
    depends_on:
      - "rabbitmq"

  subscription-api:
    image: subscription-api:0.0.1-SNAPSHOT
    container_name: subscription-api
    depends_on:
      - "mongodb"
      - "rabbitmq"

  mongodb:
    image: mongo:5.0
    ports:
      - 27017:27017
    volumes:
      - ./mongo:/data/db

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672

