server:
  port: 8081

spring:
  profiles:
    active: local

subscription:
  email:
    template: Subscription for newsletter [%s] was created for email [%s]

email:
  send-queue: send-email-queue
  feedback-queue: feedback-email-queue
